### ISSUE TITLE
[Bug]: Minor point: rogue console.log

### ISSUE THREAD

**Issue by mdcass** [spatie/livewire-filepond#10]
### What happened?

Rogue `console.log` at `/resources/views/upload.blade.php#L67`.

### How to reproduce the bug

If you publish assets

`php artisan vendor:publish --tag="livewire-filepond-views"`

You will see the `console.log` in the resulting file on line `67`.

### Package Version

1.1

### PHP Version

8.2

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS

### Notes

Unrelated to this bug (and I will raise another bug soon when I rule out it's just me being stupid) I found this `console.log` after publishing the view as I wanted to debug why my Filepond attributes aren't going through to the actual component:

```html
<x-filepond::upload
    wire:model="file"
    max-files="5"
    multiple="true"
    credits="false"
    placeholder="Why am I not seeing this?"
/>
```

But we're not seeing what i'd expect (no placeholder set, it's still single file upload):
<img width="619" alt="image" src="https://github.com/user-attachments/assets/26c65edb-ce4a-4423-93b1-a9cbbc670fb7">

**Comment by RoccoHoward** [comment]
The localization change in https://github.com/spatie/livewire-filepond/pull/8 is causing this.

placeholder is set in ` labelIdle: @js($placeholder),` (line 72)
labelIdle is also in the localization files which is then set in `pond.setOptions(@js($pondProperties));` line 79.
