### ISSUE TITLE
[Bug]: Uncaught SyntaxError: missing } after property list

### ISSUE THREAD

**Issue by iforwms** [spatie/livewire-filepond#22]
### What happened?

Install filepond with Laravel, Livewire and AplineJS, filepond error.

The error can be found here: `resources/views/vendor/livewire-filepond/upload.blade.php` lines 69 and 75 are missing  a closed bracket.

Line 69: `$dispatch('filepond-upload-reverted', {'attribute' : '{{ $wireModelAttribute }}');` should be `$dispatch('filepond-upload-reverted', {'attribute' : '{{ $wireModelAttribute }}'});`
Line 75: `$dispatch('filepond-upload-file-removed', {'attribute' : '{{ $wireModelAttribute }}');` should be `$dispatch('filepond-upload-file-removed', {'attribute' : '{{ $wireModelAttribute }}'});`

Version used: `"spatie/livewire-filepond": "^1.2"`

### How to reproduce the bug

Install filepond with Laravel, Livewire and AplineJS, filepond error - Unexpected syntax error: missing `}`.

### Package Version

1.2

### PHP Version

8.2

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS, Linux

**Comment by riasvdv** [comment]
Are you on the latest version? This should be fixed in 1.2.3
