### ISSUE TITLE
[Question]: How do we change the locale?

### ISSUE THREAD

**Issue by StanBarrows** [spatie/livewire-filepond#6]
### What happened?

Heyho

I wonder on how to set the local to a language different from English?

filepond comes already with a set of language:
https://github.com/pqina/filepond/tree/master/locale

P.S: Link to discussions is not working

![CleanShot 2024-07-24 at 00 12 57@2x](https://github.com/user-attachments/assets/f95325a8-3cbb-4dd7-b945-d5e7c0a44a5f)

### How to reproduce the bug

Try to set local to nl-nl-js

### Package Version

1.00

### PHP Version

8.4

### Laravel Version

11.0

**Comment by riasvdv** [comment]
Added in 1.1.0
